language: java
sudo: true
dist: trusty
jdk:
  - oraclejdk8
addons:
  chrome: stable
  firefox: "65.0"

git:
  depth: 2 #clone repository to a maximum depth of 2 commits

before_install:
  - google-chrome-stable --headless --no-sandbox --disable-gpu --remote-debugging-port=9222 http://localhost &
  - chmod +x src/main/resources/drivers/chromedriver
  - chmod +x src/main/resources/drivers/geckodriver

after_success:
  - mvn clean test verify install jacoco:report coveralls:report #generate Jacoco reports