language: java
sudo: false
jdk:
  - oraclejdk8

git:
  depth: 3 #clone repository to a maximum depth of 3 commits

before_install: 
  - chmod +x src/main/resources/drivers/chromedriver
  - chmod +x src/main/resources/drivers/geckodriver

after_success:
  - mvn clean install test jacoco:report coveralls:report #generate Jacoco reports